baseURL = 'https://www.captaincourageous.co.uk/'
languageCode = 'en-gb'
title = 'Captain Courageous'
theme = 'papermod'
defaultContentLanguage = 'en'
outputs = { home = ["HTML", "RSS", "JSON"] }
ignoreLogs = ['warning-goldmark-raw-html']
enableRobotsTXT = true

[markup.goldmark.renderer]
unsafe = true

[params]
  description = "UK guitar-driven band crafting upbeat anthemic tunes with irresistibly catchy hooks"
  keywords = ["Captain Courageous", "band", "music", "rock", "UK"]
  images = ["/images/CaptainCourageous_Profile_2660x1140.jpg"]
  press_kit = "/Press_Kit_Captain_Courageous.pdf"
  contact_logo_alt = "Contact Captain Courageous"
  email = "band@captaincourageous.co.uk"
  googleAnalyticsID = "G-KFXNZGN4R9"

  [[params.social]]
    name = "Instagram"
    url = "https://www.instagram.com/captaincourageousband"
    icon = "fa-brands fa-instagram"
    handle = "@CaptainCourageousBand"

  [[params.social]]
    name = "Facebook"
    url = "https://www.facebook.com/profile.php?id=61585847815298"
    icon = "fa-brands fa-facebook"
    handle = "CaptainCourageousBand"

  [[params.social]]
    name = "TikTok"
    url = "https://www.tiktok.com/@captain.courageous"
    icon = "fa-brands fa-tiktok"
    handle = "@Captain.Courageous"

  [[params.social]]
    name = "X"
    url = "https://x.com/CourageousMusic"
    icon = "fa-brands fa-x-twitter"
    handle = "@CourageousMusic"

  [[params.social]]
    name = "YouTube"
    url = "https://www.youtube.com/@CaptainCourageousMusic"
    icon = "fa-brands fa-youtube"
    handle = "@CaptainCourageousMusic"

  [[params.social]]
    name = "Linktree"
    url = "https://linktr.ee/captaincourageous"
    icon = "fa-solid fa-link"
    handle = "Linktree"

  [params.label]
    icon = "/images/Logo_BW.png"
    iconHeight = 36
    text = ""

  [params.labelOrg]
    name = "Through a Prism"
    url = "https://www.throughaprism.co.uk/"

  [params.assets]
    favicon = "/favicon.svg"
    safari_pinned_tab = "/favicon.svg"
    apple_touch_icon = "/images/Logo_BW.png"
    favicon32x32 = "/images/Logo_BW.png"
    favicon16x16 = "/images/Logo_BW.png"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 2

  [[menu.main]]
    name = "Music"
    url = "music/"
    weight = 3

  [[menu.main]]
    name = "Contact"
    url = "contact/"
    weight = 4

  [[menu.main]]
    name = "Merch"
    url = "https://captain-courageous.square.site"
    weight = 5
